export const products = [
    {
        id: 1,
        image: "FCE.jpg",
        nombreProducto: "Preparación para FCE",
        categoria: "Exámenes",
        precio: 4200,
        stock: 20,
    },
    {
        id: 2,
        image: "CursoConversación.jpg",
        nombreProducto: "Inglés conversacional",
        categoria: "Otros",
        precio: 5000,
        stock: 20,
    },
    {
        id: 3,
        image: "IELTS.jpg",
        nombreProducto: "Preparación para IELTS",
        categoria: "Exámenes",
        precio: 6000,
        stock: 20,
    },
    {
        id: 4,
        image: "CursoAdolescentes.jpg",
        nombreProducto: "Inglés para adolescentes",
        categoria: "Jóvenes",
        precio: 4300,
        stock: 20,
    },
    {
        id: 5,
        image: "CursoNiños.jpg",
        nombreProducto: "Inglés para niños",
        categoria: "Jóvenes",
        precio: 5200,
        stock: 20,
    },
];
